# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            K3K's Hideout
tagline:          'I just want to be a cat'
description:      "A random cat's attempt at learning computer programming."
url:              https://gamer2810.github.io/
baseurl:          /

author:
  name:           'Kha Tran'
  url:            https://www.facebook.com/minh.kha.1441

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

theme: jekyll-theme-cayman